<a href="https://colab.research.google.com/github/endar1y12/ML/blob/main/ML_meet_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

print(iris_ku) # termasuk ke dalam data independent
#target sebagai label

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
#simpan data fitur/kolom x dan target y
x = iris_ku.data
y=iris_ku.target

#simpan nama fitur x dan target y
feature_names =iris_ku.feature_names
target_names = iris_ku.target_names

#tampil nama fitur dan target dataset
print("Feature names:",feature_names)
print("Target names:",target_names)




Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [3]:
# x dan y adalah numpy arrays
print("\nType of X is",type(x))

#tampilkan 5 baris pertama
print("\nfirst 5 rows of X:\n", x[:5])




Type of X is <class 'numpy.ndarray'>

first 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [4]:
#fitur x dan target y
x = iris_ku.data
y=iris_ku.target

print(x)
print(y)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
#spitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split
x_latih,x_tes,y_latih,y_tes = train_test_split(x,y,test_size = 0.4,random_state=1)

# print(x_tes)


In [6]:
#tampilkan data fitur latih dan uji
print(x_latih.shape)
print(x_tes.shape)



(90, 4)
(60, 4)


In [7]:
#tampilkan data target latih dan uji
print(y_latih.shape)
print(y_tes.shape)



(90,)
(60,)


In [8]:
#pelatihan pada data latih menggunakan KNN k =3
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_latih,y_latih)



KNeighborsClassifier(n_neighbors=3)

In [9]:
#melakukan prediksi pada data uji
y_prediksi = knn.predict(x_tes)



In [10]:
#perbandingan nilai aktual y_tes dengan nilai prediksi y_prediksi
from sklearn import metrics
print("Akurasi model kNN:",metrics.accuracy_score(y_tes,y_prediksi))



Akurasi model kNN: 0.9833333333333333


In [11]:
#prediksi menggunakan data sampel dibuat sendiri
contoh = [[3,5,4,2],[2,3,5,4]]
preds = knn.predict(contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print("Prediksi :",pred_species)



Prediksi : ['versicolor', 'virginica']


In [12]:
# #saving the model
# from sklearn.externals import extjoblib
# import joblib

# joblib.dump (knn,'iris_knn.pkl')